---
settings:
parallel: true

driver: 
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-logging::server_es]
    - recipe[ktc-logging::server_logstash]
    - recipe[ktc-logging::server_kibana]
    - recipe[ktc-logging::client]
    - recipe[ktc-logging::logging]
  attributes: 
    etcd:
      servers:
        - 127.0.0.1
    ha_disabled: true
    logstash:
      elasticsearch_cluster: 'es-cluster-test'
    elasticsearch:
      cluster:
        name: 'es-cluster-test'
