---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
    customize:
      cpus: 2
      memory: 1024
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
    customize:
      cpus: 2
      memory: 1024

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[ktc-logging::server_logstash]
    - recipe[ktc-logging::server_es]
    - recipe[ktc-logging::client]
  attributes: 
    logging:
      recipes_server_logstash: 
        - ktc-logging::logstash
      recipes_server_es: 
        - elasticsearch::default
        - logstash::index_cleaner
    logstash:
      elasticsearch_cluster: 'es-cluster-test'
    elasticsearch:
      cluster:
        name: 'es-cluster-test'
